name: Build site
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 3,5,14,18 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          DARK_VISITOR_TOKEN: ${{ secrets.DARK_VISITOR_TOKEN }}

      - name: Add cname
        run: npm run deploy:cname

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
