name: Build site
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 3,5,14,18 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: Add cname
        run: npm run deploy:cname

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
